# Generated by Django 3.2.13 on 2022-05-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_features_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
